# Form implementation generated from reading ui file './calculator.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(326, 560)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #0d1117;\n"
"}")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(42)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    font-family: \"Noto Sans\";\n"
"    font-size: 42px;\n"
"    font-weight: normal;\n"
"\n"
"    color: white;\n"
"    background-color: #05070f;\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    padding-right: 20px;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.AC = QtWidgets.QPushButton(parent=Dialog)
        self.AC.setGeometry(QtCore.QRect(10, 170, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.AC.setFont(font)
        self.AC.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(98, 98, 98);\n"
"color: rgb(158, 158, 158);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a7a7a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a5a5a;\n"
"}")
        self.AC.setObjectName("AC")
        self.C = QtWidgets.QPushButton(parent=Dialog)
        self.C.setGeometry(QtCore.QRect(90, 170, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.C.setFont(font)
        self.C.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(98, 98, 98);\n"
"color: rgb(158, 158, 158);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a7a7a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a5a5a;\n"
"}")
        self.C.setObjectName("C")
        self.division = QtWidgets.QPushButton(parent=Dialog)
        self.division.setGeometry(QtCore.QRect(170, 170, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.division.setFont(font)
        self.division.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(25, 99, 190);\n"
"color: rgb(80, 194, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 115, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(21, 83, 154);\n"
"}")
        self.division.setObjectName("division")
        self.equal = QtWidgets.QPushButton(parent=Dialog)
        self.equal.setGeometry(QtCore.QRect(250, 450, 71, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.equal.setFont(font)
        self.equal.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(61, 187, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5cc2ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2d9be6;\n"
"}")
        self.equal.setObjectName("equal")
        self.btn9 = QtWidgets.QPushButton(parent=Dialog)
        self.btn9.setGeometry(QtCore.QRect(170, 250, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn9.setObjectName("btn9")
        self.btn6 = QtWidgets.QPushButton(parent=Dialog)
        self.btn6.setGeometry(QtCore.QRect(170, 330, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn6.setObjectName("btn6")
        self.btn3 = QtWidgets.QPushButton(parent=Dialog)
        self.btn3.setGeometry(QtCore.QRect(170, 410, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn3.setObjectName("btn3")
        self.decimal = QtWidgets.QPushButton(parent=Dialog)
        self.decimal.setGeometry(QtCore.QRect(170, 490, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.decimal.setFont(font)
        self.decimal.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.decimal.setObjectName("decimal")
        self.btn2 = QtWidgets.QPushButton(parent=Dialog)
        self.btn2.setGeometry(QtCore.QRect(90, 410, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn2.setObjectName("btn2")
        self.btn5 = QtWidgets.QPushButton(parent=Dialog)
        self.btn5.setGeometry(QtCore.QRect(90, 330, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn5.setObjectName("btn5")
        self.btn0 = QtWidgets.QPushButton(parent=Dialog)
        self.btn0.setGeometry(QtCore.QRect(10, 490, 151, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn0.setObjectName("btn0")
        self.btn1 = QtWidgets.QPushButton(parent=Dialog)
        self.btn1.setGeometry(QtCore.QRect(10, 410, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn1.setObjectName("btn1")
        self.btn8 = QtWidgets.QPushButton(parent=Dialog)
        self.btn8.setGeometry(QtCore.QRect(90, 250, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn8.setObjectName("btn8")
        self.btn4 = QtWidgets.QPushButton(parent=Dialog)
        self.btn4.setGeometry(QtCore.QRect(10, 330, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn4.setObjectName("btn4")
        self.btn7 = QtWidgets.QPushButton(parent=Dialog)
        self.btn7.setGeometry(QtCore.QRect(10, 250, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);\n"
"color: rgb(34, 133, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #404040;\n"
"}")
        self.btn7.setObjectName("btn7")
        self.multiplication = QtWidgets.QPushButton(parent=Dialog)
        self.multiplication.setGeometry(QtCore.QRect(250, 170, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.multiplication.setFont(font)
        self.multiplication.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(25, 99, 190);\n"
"color: rgb(80, 194, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 115, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(21, 83, 154);\n"
"}")
        self.multiplication.setObjectName("multiplication")
        self.substraction = QtWidgets.QPushButton(parent=Dialog)
        self.substraction.setGeometry(QtCore.QRect(250, 250, 71, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        self.substraction.setFont(font)
        self.substraction.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(25, 99, 190);\n"
"color: rgb(80, 194, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 115, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(21, 83, 154);\n"
"}")
        self.substraction.setObjectName("substraction")
        self.addition = QtWidgets.QPushButton(parent=Dialog)
        self.addition.setGeometry(QtCore.QRect(250, 330, 71, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(30)
        font.setBold(True)
        self.addition.setFont(font)
        self.addition.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(25, 99, 190);\n"
"color: rgb(80, 194, 255);\n"
"font-size: 30px;\n"
"font-family: SF Pro Display;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 115, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(21, 83, 154);\n"
"}")
        self.addition.setObjectName("addition")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AC.setText(_translate("Dialog", "AC"))
        self.C.setText(_translate("Dialog", "C"))
        self.division.setText(_translate("Dialog", "/"))
        self.equal.setText(_translate("Dialog", "="))
        self.btn9.setText(_translate("Dialog", "9"))
        self.btn6.setText(_translate("Dialog", "6"))
        self.btn3.setText(_translate("Dialog", "3"))
        self.decimal.setText(_translate("Dialog", "."))
        self.btn2.setText(_translate("Dialog", "2"))
        self.btn5.setText(_translate("Dialog", "5"))
        self.btn0.setText(_translate("Dialog", "0"))
        self.btn1.setText(_translate("Dialog", "1"))
        self.btn8.setText(_translate("Dialog", "8"))
        self.btn4.setText(_translate("Dialog", "4"))
        self.btn7.setText(_translate("Dialog", "7"))
        self.multiplication.setText(_translate("Dialog", "*"))
        self.substraction.setText(_translate("Dialog", "-"))
        self.addition.setText(_translate("Dialog", "+"))
